version: '3.8'

services:
  app:
    image: oven/bun:1
    ports:
      - 3000:3000
    
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=whattheshit
    volumes:
      - postgres:/var/lib/postgresql/data

